module.exports={
    getcartlistInfoById(){
        let mycartlistProject={
            cartlistheader:{
                "cartlistheaderpic":"http://47.94.149.181/dc0517/cartlist/13.jpg"
            },
            carlists:[
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/14.jpg",
                    "carlistname":"哈弗M6",
                    "carlisttitle":"至高享8500元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/12.jpg",
                    "carlistname":"哈弗H6运动版",
                    "carlisttitle":"至高享28000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/11.jpg",
                    "carlistname":"新哈弗H9(除2020款)",
                    "carlisttitle":"至高享32000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/10.jpg",
                    "carlistname":"2019款全新哈弗H6",
                    "carlisttitle":"至高享18000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/2.jpg",
                    "carlistname":"新哈弗H6 Coupe智联版",
                    "carlisttitle":"至高享15500元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/6.jpg",
                    "carlistname":"哈弗H2创想版",
                    "carlisttitle":"至高享7500元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/3.jpg",
                    "carlistname":"哈弗F5",
                    "carlisttitle":"至高享10000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/4.jpg",
                    "carlistname":"哈弗F7",
                    "carlisttitle":"至高享18000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/9.jpg",
                    "carlistname":"哈弗H5经典版",
                    "carlisttitle":"至高享4000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/5.jpg",
                    "carlistname":"哈弗H4智联版",
                    "carlisttitle":"至高享10000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/7.jpg",
                    "carlistname":"2018款新哈弗H7",
                    "carlisttitle":"至高享38000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                },
                {
                    "carlistpic":"http://47.94.149.181/dc0517/cartlist/8.jpg",
                    "carlistname":"哈弗H7L",
                    "carlisttitle":"至高享38000元综合钜惠",
                    "carlistprice":"¥499",
                    "carbtn":"立即订购"
                }
            ],
            cartlistcards:{
                "cartlistcard":"http://47.94.149.181/dc0517/cartlist/1.jpg"
            },
            cartlistfooter:{
                "cartlistfootername":"我要买车"
            }
        }
        return mycartlistProject
    }
}