module.exports={
    homeInfo(){
        let myhomeProject={
            section:{
                homeoptions:[
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/2.jpg",
                        "nameoptions":"车抢购"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/3.jpg",
                        "nameoptions":"安心换"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/4.jpg",
                        "nameoptions":"车享用"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/5.jpg",
                        "nameoptions":"车联网"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/35.jpg",
                        "nameoptions":"车延保"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/6.jpg",
                        "nameoptions":"领券吧"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/36.jpg",
                        "nameoptions":"车互动"
                    },
                    {
                        "picoptions":"/hafo-webapp/src/assets/home/7.jpg",
                        "nameoptions":"找好店"
                    }
                ],
                news:{
                    "newsname":"哈弗",
                    "newsdynamic":"动态",
                    "newsdate":"最新"
                },
                iovs:[
                    {"piciovs":"/hafo-webapp/src/assets/home/8.jpg"},
                    {"piciovs":"/hafo-webapp/src/assets/home/37.jpg"},
                    {"piciovs":"/hafo-webapp/src/assets/home/38.jpg"}
                ],
                cartitles:[
                    {
                        "cartitlesname":"车抢购",
                        "cartitlesanymore":"更多>"
                    },
                    {
                        "cartitlesname":"安心换",
                        "cartitlesanymore":"更多>"
                    },
                    {
                        "cartitlesname":"车享用",
                        "cartitlesanymore":"更多>"
                    },
                    {
                        "cartitlesname":"车延保",
                        "cartitlesanymore":"更多>"
                    },
                    {
                        "cartitlesname":"车互动",
                        "cartitlesanymore":"更多>"
                    }
                ],
                purchasecards:[
                    {"picpurchasecard":"/hafo-webapp/src/assets/home/39.jpg"},
                    {"picpurchasecard":"/hafo-webapp/src/assets/home/9.jpg"},
                    {"picpurchasecard":"/hafo-webapp/src/assets/home/13.jpg"},
                    {"picpurchasecard":"/hafo-webapp/src/assets/home/14.jpg"}
                ],
                purchaselists:[
                    {
                        "carlist":"/hafo-webapp/src/assets/home/10.jpg",
                        "purchasetitle":"2019款全新哈弗H6",
                        "purchaseorder":"订:",
                        "order":"¥499",
                        "purchaseprice":"官方指导价:109000起",
                        "selectlists":{
                            "enquiry":"询价",
                            "drive":"试驾",
                            "buy":"订购",
                            "substitution":"置换"
                        }
                    },
                    {
                        "carlist":"/hafo-webapp/src/assets/home/11.jpg",
                        "purchasetitle":"新哈弗H6 Coupe智联版",
                        "purchaseorder":"订:",
                        "order":"¥499",
                        "purchaseprice":"官方指导价:103000起",
                        "selectlists":{
                            "enquiry":"询价",
                            "drive":"试驾",
                            "buy":"订购",
                            "substitution":"置换"
                        }
                    },
                    {
                        "carlist":"/hafo-webapp/src/assets/home/10.jpg",
                        "purchasetitle":"哈弗M6",
                        "purchaseorder":"订:",
                        "order":"¥499",
                        "purchaseprice":"官方指导价:66000起",
                        "selectlists":{
                            "enquiry":"询价",
                            "drive":"试驾",
                            "buy":"订购",
                            "substitution":"置换"
                        }
                    }
                ],
                "backgrounds":"/hafo-webapp/src/assets/home/15.jpg",
                "enjoys":[
                    {
                        "newgoods":"新品",
                        "enjoysname":"轻盈小果冻旅行箱",
                        "enjoyprice":"¥186",
                        "beforprice":"199",
                        "person":"96",
                        "personfont":"人关注"
                    },
                    {
                        "newgoods":"新品",
                        "enjoysname":"户外速开帐篷",
                        "enjoyprice":"¥167",
                        "beforprice":"179",
                        "person":"119",
                        "personfont":"人关注"
                    }
                ],
                "interactlists":[
                    {
                        "interactfont":"要晒就晒不一样的哈弗人，九点集合准时出发，路上随便拍的几张，安全第一，很快了此行目...",
                        "users":"h***o",
                        "follownum":"78"
                    },
                    {
                        "interactfont":"自从购入了二哈，往返老家与工作地，再也不用挤拥挤不堪的公交车，再也不用半夜里父亲...",
                        "users":"我***y",
                        "follownum":"24"
                    },
                    {
                        "interactfont":"又是一年最好时，迎着春风，踏着暖浪，徜徉在抚仙湖畔。湖光山色配上...",
                        "users":"我***车",
                        "follownum":"14"
                    },
                    {
                        "interactfont":"六弟陪我个把月了。在崎岖蜿蜒的道路上，陪我一起风风雨雨，勇往直前，笑看前方路。",
                        "users":"梦***醒",
                        "follownum":"62"
                    }
                ]
            }
        }
    }
}